import { electroArtwork } from './electro-scene.js';
export { electroArtwork } from './electro-scene.js';
import { EC, IONS, ELECTRODES, ELECTRODE, ELECTROLYTES, PREDICTIONS, TERMINALS, ELECTRO_SOURCES } from './electro-data.js';
import { electroPreview, metalMass, gasVolume } from './electro-model.js';
import { electroCalculations } from './electro-analysis.js';
import { escapeHTML as esc } from './lab-shelf.js';
import { EQUIPMENT } from './lab-data.js';
const f=(n,d=4)=>Number.isFinite(n)?Number(n.toPrecision(d)).toLocaleString('en-US',{maximumSignificantDigits:d}):'—';
const button=(action,label,extra='')=>`<button type="button" class="sl-button" data-electro="${action}" ${extra}>${label}</button>`;
const input=(name,label,value,min,max,step='any')=>`<label>${esc(label)}<input type="number" name="${name}" value="${value}" min="${min}" max="${max}" step="${step}" required></label>`;
const select=(name,label,options,selected)=>`<label>${esc(label)}<select name="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
const check=(name,label,value)=>`<label class="sl-check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(label)}</label>`;
const form=(fields,action,label,extra='')=>`<form class="el-form"><div class="sl-controls">${fields}</div>${button(action,label,extra)}</form>`;
const table=(headers,rows)=>`<div class="sl-table-wrap"><table class="sl-table"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">No recorded results yet.</td></tr>`}</tbody></table></div>`;
const calc=(text)=>`<details class="el-calculation"><summary>Show calculation</summary><p>${esc(text)}</p></details>`;
const card=(title,body,id='')=>`<section class="sl-panel el-card" ${id?`id="${id}"`:''}><h2>${title}</h2>${body}</section>`;
function electroChart(rows,x,series,label){
  if(!rows.length)return '<p class="sl-small">Run the instrument or advance time to build this graph.</p>';
  const xs=rows.map(r=>r[x]),ys=rows.flatMap(r=>series.map(s=>r[s.key])).filter(Number.isFinite);
  const minX=Math.min(...xs),maxX=Math.max(...xs),low=Math.min(...ys),high=Math.max(...ys);
  const xRange=Math.max(maxX-minX,1e-9),padding=Math.max((high-low)*.05,high===low?Math.max(Math.abs(high)*.01,.001):1e-12),minY=low-padding,maxY=high+padding;
  const axis=n=>Math.abs(n)>1e6||(n!==0&&Math.abs(n)<.001)?n.toExponential(2):Number(n.toPrecision(6)).toString();
  // Preserve endpoints and local extrema while keeping long-run SVGs small.
  const indices=new Set([0,rows.length-1]),bucket=Math.max(1,Math.ceil(rows.length/250));
  for(let start=0;start<rows.length;start+=bucket)for(const s of series){let low=start,high=start;for(let i=start;i<Math.min(rows.length,start+bucket);i++){if(rows[i][s.key]<rows[low][s.key])low=i;if(rows[i][s.key]>rows[high][s.key])high=i;}indices.add(low);indices.add(high);}
  const plotted=rows.length>600?[...indices].sort((a,b)=>a-b).map(i=>rows[i]):rows;
  return `<figure class="og-plot"><svg viewBox="0 0 600 210" role="img" aria-label="${esc(label)}"><path d="M82 12V167H582" fill="none" stroke="#a5b8ad"/>${[0,.5,1].map(t=>`<text x="74" y="${171-t*153}" text-anchor="end">${axis(minY+t*(maxY-minY))}</text><text x="${82+t*500}" y="189" text-anchor="middle">${axis(minX+t*(maxX-minX))}</text>`).join('')}${series.map((s,i)=>`<polyline fill="none" stroke="${['#285d60','#aa6935','#8975a2'][i%3]}" stroke-width="2" points="${plotted.filter(r=>Number.isFinite(r[s.key])).map(r=>`${82+(r[x]-minX)/xRange*500},${167-(r[s.key]-minY)/(maxY-minY)*153}`).join(' ')}"/>`).join('')}</svg><figcaption>${esc(label)}${series.length>1?` · ${series.map(s=>esc(s.name)).join(' / ')}`:''}</figcaption></figure>`;
}
const chart=(rows,x,key,name)=>electroChart(rows,x,[{key,name}],name);

function controls(e,selected){
  const cfg=e.config,stock=ELECTROLYTES.find(x=>x.catalogId===selected),selectedElectrode=selected.startsWith('electro:electrode-')?selected.replace('electro:electrode-',''):null;
  return card('Prepare the cell',`<p>Use the same shelf and glassware as the rest of the lab. Fill an empty cell, combine supported electrolyte increments, or transfer an actual aliquot from a bench vessel. Final-volume preparation assumes additive solutes with negligible volume change.</p>
    <div class="el-two">${form(input('volume','Distilled water / cell volume (mL)',200,10,1000),'fill','Fill empty cell')}${form(select('vessel','Source vessel',EQUIPMENT.filter(x=>x.id!=='filter').map(x=>[x.id,x.name]),'beaker')+input('ml','Aliquot to transfer (mL)',25,.1,250),'import-vessel','Transfer aliquot to cell')}</div>
    ${form(select('stock','Electrolyte · shared chemical database',ELECTROLYTES.map(s=>[s.id,s.name]),stock?.id||'sodium-sulfate')+input('concentration','Added concentration (mol/L)',.1,0,1)+select('side','Compartment',[['both','Both / undivided'],['left','Left only'],['right','Right only']],'both'),'add-solute','Add electrolyte to cell')}
    <p class="sl-small">${e.volume?`${f(e.volume)} mL in this cell.`:'Cell is empty.'} Choose a divided cell below before preparing different half-cell solutions. Changing starting materials after a timed run requires a new cell trial.</p>
    <div class="el-two">${['left','right'].map(side=>form(`<input type="hidden" name="side" value="${side}">`+select('material',`${side} electrode`,ELECTRODES.map(x=>[x.id,x.name]),selectedElectrode||e.electrodes[side].material)+input('mass','Starting electrode mass (g)',e.electrodes[side].initialMass,.01,100),'electrode',`Fit ${side} electrode`)).join('')}</div>
    ${table(['Mounted electrode','Reference potential','Bulk conductivity','Surface / corrosion model'],['left','right'].map(side=>{const m=ELECTRODE[e.electrodes[side].material];return [esc(side+' · '+m.name),m.ion?`${IONS[m.ion].E} V vs SHE (${esc(m.ion)} ion/metal, standard reduction)`:'No unique material potential; see each reaction couple',`${f(m.conductivity)} S/m (representative)`,esc(m.note)];}))}
    <details><summary>Cell geometry, separator, stirring and heating</summary>${form(input('leftArea','Left wetted area (cm²)',cfg.leftArea,.1,100)+input('rightArea','Right wetted area (cm²)',cfg.rightArea,.1,100)+input('spacing','Electrode spacing (cm)',cfg.spacing,.1,20)+select('separator','Cell / separator',[['none','Undivided cell'],['porous','Divided · porous separator'],['bridge','Two compartments · salt bridge'],['cation','Divided · cation-exchange membrane'],['anion','Divided · anion-exchange membrane']],cfg.separator)+input('membraneResistance','Separator resistance (Ω)',cfg.membraneResistance,0,500)+check('stirring','Magnetic stirrer',cfg.stirring)+check('heating','Heating plate',cfg.heating)+input('plateTemperature','Plate target (°C)',cfg.plateTemperature,20,80)+input('temperature','Initial temperature (°C)',e.temperature,5,70)+check('sealed','Explore a sealed gas space (pressure hazard)',cfg.sealed)+input('headspace','Virtual headspace (mL)',cfg.headspace,1,1000),'configure','Apply cell settings')}<p class="sl-small">Initial temperature and separator changes are locked after a timed run. Use the separate supply controls during an existing run. pH is compartment-averaged, not a resolved surface pH.</p></details>`,'el-preparation');
}
function predictionControls(e,draft){
  const values={...e.predictions,...draft},count=PREDICTIONS.filter(([id])=>String(values[id]||'').trim()).length;
  return `<section class="el-start-check" id="el-predictions" aria-labelledby="el-prediction-heading"><p id="el-prediction-heading"><strong>${count===7?'Predictions ready':'Before starting'}</strong> · <span id="el-prediction-count">${count} of 7 predictions prepared</span></p>${count<7?'<p class="sl-small">Write what you expect, or explicitly mark unanswered predictions as uncertain.</p>':''}
    ${button('run-uncertain','Mark unanswered uncertain & start',`id="el-start-uncertain" form="el-supply-form" ${count===7?'hidden':''}`)}
    <details id="el-prediction-details"><summary>Write or review predictions</summary><form class="el-form" id="el-prediction-form"><div class="el-predictions">${PREDICTIONS.map(([id,label])=>`<label>${esc(label)}<textarea id="el-prediction-${id}" name="${id}" rows="2" maxlength="2000" required>${esc(values[id])}</textarea></label>`).join('')}</div><div class="sl-row">${button('predictions','Record my predictions')}${button('uncertain','Mark unanswered as uncertain')}</div></form></details>
    <p id="el-start-feedback" class="sl-warning" role="alert" hidden></p>
  </section>`;
}
function circuitControls(e,selectedTerminal){
  const name=id=>TERMINALS.find(([key])=>key===id)?.[1];
  return `<section id="el-circuit" class="el-circuit-controls"><h3>Connect the circuit</h3><p id="el-wire-hint" class="sl-small" role="status">${e.power?'Stop the output before changing wires.':selectedTerminal?`${esc(name(selectedTerminal))} selected. Choose the other terminal.`:'Click two terminals in the drawing to add a wire.'}</p>
    <div class="sl-row">${button('standard-wires','Use standard wiring',e.power?'disabled':'')}${selectedTerminal?button('cancel-wire','Cancel wire'):''}</div>
    <details><summary>Wire list & terminal selectors · ${e.wires.length}</summary>${form(select('from','From terminal',TERMINALS,selectedTerminal||'plus')+select('to','To terminal',TERMINALS,'a-plus'),'wire','Connect wire',e.power?'disabled':'')}
    <ul class="el-wires">${e.wires.map(([a,b],i)=>`<li><span>${esc(name(a))} → ${esc(name(b))}</span>${button('remove-wire','Remove',`data-index="${i}" aria-label="Remove wire ${i+1}" ${e.power?'disabled':''}`)}</li>`).join('')||'<li>No wires connected.</li>'}</ul></details></section>`;
}
function supply(e,running,selectedTerminal,draft,predictionDraft){
  const cfg={...e.config,...draft},p=electroPreview(e),field=(name,label,min,max,step='any')=>input(name,label,cfg[name],min,max,step).replace('<input ',`<input id="el-supply-${name}" `);
  return `<section class="el-control-dock" id="el-power" aria-label="Cell controls"><div class="el-dock-heading"><h2>Power & timing</h2><span class="el-output-state ${e.power?'is-on':''}">${running?'RUNNING':e.power?'OUTPUT ON':'STOPPED'}</span></div>
    <p class="el-circuit-status">${esc(p.wiring.status)} · ${esc(p.regulation)}</p>
    <form class="el-form el-supply-form" id="el-supply-form">
      ${select('mode','Supply mode',[['cv','Constant voltage'],['cc','Constant current'],['galvanic','Galvanic load']],cfg.mode).replace('<select ','<select id="el-supply-mode" ')}
      <div class="el-voltage-control">${field('voltage','Voltage / CC compliance (V)',0,30,.1)}<input id="el-voltage-range" type="range" min="0" max="30" step="0.1" value="${cfg.voltage}" aria-label="Voltage dial, volts"><div class="el-range-scale"><span>0 V</span><span>30 V</span></div></div>
      <div class="el-supply-pair">${field('limit','Current limit (A)',0,5,.01)}${field('current','CC target (A)',0,5,.01)}</div>
      <details><summary>Load & recording</summary><div class="el-supply-pair">${field('load','Load (Ω)',.1,10000)}${field('sampleInterval','Record every (s)',1,60,1)}</div></details>
      ${button('supply','Apply supply settings','id="el-apply-supply"')}<span class="el-draft-status" id="el-supply-status">${draft?'Unapplied changes':'Settings applied'}</span>
    </form>
    ${predictionControls(e,predictionDraft)}
    <div class="el-run-buttons">${button('run',running?'Running…':'Start',`id="el-start" form="el-supply-form" ${running?'disabled':''}`)}${button('pause','Stop',`id="el-stop" ${running||e.power?'':'disabled'}`)}</div>
    <div class="el-live-summary"><span>Time <strong data-el-live="time">${f(e.time)} s</strong></span><span>Charge <strong data-el-live="charge">${f(e.charge)} C</strong></span></div>
    <label>Time speed<select id="el-speed"><option value="1">4 simulated seconds / second</option><option value="10">40 simulated seconds / second</option><option value="60" selected>240 simulated seconds / second</option></select></label>
    ${p.unsupported?`<p class="sl-warning">${esc(p.unsupported)}</p>`:''}${e.stopReason?`<p class="sl-warning">${esc(e.stopReason)}</p>`:''}
    ${circuitControls(e,selectedTerminal)}
    <details class="el-manual-time"><summary>Manual steps & instruments</summary><div class="sl-row">${button('power',`Switch output ${e.power?'off':'on'}`)}${button('measure','Read all instruments')}${button('new-cell','New cell trial')}</div>${form(input('seconds','Advance simulation (s)',60,1,3600,1),'advance','Advance & record')}<p class="sl-small">Start records your prepared predictions, applies the visible supply settings and runs the timer. Stop pauses time and switches output off. Readings and contents are kept.</p></details>
  </section>`;
}
function consoleView(e,running,selectedTerminal,draft,predictionDraft){return `<section class="el-console sl-panel" aria-label="Interactive electrochemistry bench">${electroArtwork(e,running,selectedTerminal,true)}${supply(e,running,selectedTerminal,draft,predictionDraft)}</section>`;}
function results(e){
  const a=electroCalculations(e),p=a.preview,last=e.records.at(-1);
  return card('Competing half reactions',`<p>Standard potentials use reduction convention vs SHE, even for reactions running in oxidation. Activities are approximated by molar concentrations; gases have unit reference fugacity in Nernst calculations. Kinetic constants are editable teaching assumptions.</p><p class="og-equation">${esc(p.overall)}</p><p class="sl-small">Displayed overall equation combines the dominant pair. Parallel reactions are accounted for by their separate partial charges.</p>
    ${['anode','cathode'].map(role=>`<h3>${role==='anode'?'Anode · oxidation':'Cathode · reduction'}</h3>${table(['Reaction','E° / Eeq (V)','Partial current / share','Limiting current','Calculation'],p[role].reactions.map(r=>[esc(r.label),`${f(r.E0)} / ${f(r.E)}`,`${f(r.current)} A / ${f(100*r.share)}%`,Number.isFinite(r.limit)?`${f(r.limit)} A`:'Water branch: not diffusion capped',calc(`E = E° − RT/(nF) ln Q = ${r.E0} − (${EC.R} × ${e.temperature+273.15})/(${r.n} × ${EC.F}) ln(${r.Q}) = ${r.E} V. Q uses dimensionless ideal activities at a 1 mol/L standard state. i₀=${r.i0} A/cm², A=${r.A} cm². Ikin=2Ai₀sinh(Fη/2RT); partial I=Ikin Ilim/(Ikin+Ilim). Ilim=nFADC/δ for soluble reactants. Diagnostic concentration polarization = ${f(r.concentrationEta)} V. The largest partial current is dominant; this need not be the reaction with the most favorable E°.`)]))}`).join('')}
    <p class="sl-small">At a neutral/basic cathode the hydrogen half reaction can equivalently be written 2 H₂O + 2 e⁻ → H₂ + 2 OH⁻. The table uses the acid-form standard potential consistently with its reaction quotient.</p>
    ${table(['Compartment','Dissolved species (mol/L)','Equilibrium solids (mol)'],['left','right'].map(side=>{const s=p.solutions[side];return [side,esc(Object.entries(s.free).filter(([,n])=>n>1e-12).map(([id,n])=>`${id}: ${f(n)}`).join('; ')||'Water autoionization only'),esc([...Object.entries(s.solid).filter(([,n])=>n>1e-12).map(([id,n])=>`${id}(OH)${IONS[id].z}: ${f(n)}`),...(s.agcl>1e-12?[`AgCl: ${f(s.agcl)}`]:[])].join('; ')||'None predicted')];}))}<p class="sl-small">Hydroxide and AgCl equilibria are limited ideal approximations; oxidation states, hydroxide complexes and concentrated chloride speciation are not exhaustively modeled.</p>`)+
    card('Meters and transparent calculations',`<div class="el-calculations">${a.metrics.map(([name,value,unit,equation])=>`<article><small>${esc(name)}</small><strong>${f(value)} <span>${esc(unit)}</span></strong>${calc(equation)}</article>`).join('')}</div>${last?`<h3>Stored digital instrument readings</h3>${table(['Instrument','Reading','Uncertainty / connection'],[['Voltmeter',`${f(last.measured.voltage)} V`,p.wiring.meterSign?'±0.01 V; sign follows leads':'Not connected across the cell'],['Ammeter',`${f(last.measured.ammeter)} A`,p.wiring.ammeter?'±0.001 A; in series':'Bypassed or not connected in series'],['Multimeter · current / resistance',`${f(last.measured.current)} A / ${f(p.resistance)} Ω`,'Current is a stored supply-channel reading; resistance is a calculated de-energized-cell estimate, not an ohmmeter reading on a live circuit.'],['Temperature probe',`${f(last.measured.temperature)} °C`,'±0.2 °C'],['pH meter · left / right',`${f(last.measured.leftPH)} / ${f(last.measured.rightPH)}`,'±0.02 pH'],['Conductivity meter',`${f(last.measured.conductivity*1000)} mS/cm`,'±2% of estimate'],['Electronic balance · left / right',`${f(last.measured.leftMass)} / ${f(last.measured.rightMass)} g`,'±0.001 g per reading']])}`:'<p>Use “Read all instruments” or advance time to record observations.</p>'}`,'el-measurements')+
    card('Faraday’s law, collection and mass balance',`${table(['Side / reaction','100% current-efficiency mass','Modeled reacted mass','Current efficiency','Calculation'],a.deposition.map(r=>[esc(`${r.side} · ${r.id} ${r.direction}`),`${f(r.theoretical)} g`,`${f(r.actual)} g`,`${f(r.efficiency)}%`,calc(r.formula)]))}
    ${table(['Electrode','Predicted net mass change','Measured net mass change','Percentage error'],a.massComparison.map(m=>[m.side,`${f(m.predicted)} g`,`${f(m.measured)} g`,`${f(m.error)}%`]))}${calc('Measured change = final balance reading − initial balance reading. Percentage error = 100 × (measured change − predicted change)/|predicted change|. Undefined for zero predicted change; two ±0.001 g balance readings contribute uncertainty.')}
    ${table(['Gas','100% mol / actual mol','Evolved dry volume','Stored collected reading','Error vs evolved / efficiency','Calculation'],a.gases.map(g=>[g.id,`${f(g.theoretical)} / ${f(g.actual)}`,`${f(g.volume)} mL`,`${f(g.measured)} mL`,`${f(g.error)}% / ${f(g.efficiency)}%`,calc(g.formula)]))}
    <p>Hydrogen:oxygen molar ratio = ${e.gases.O2?f(e.gases.H2/e.gases.O2):'not determined'}. Pure water splitting predicts 2:1; competing metal or chloride reactions can change this ratio.</p>${calc(`n(H₂)/n(O₂) = [Q_H₂/(2F)]/[Q_O₂/(4F)] = 2 Q_H₂/Q_O₂. This equals 2 only when both gas branches carry equal charge.`)}
    ${table(['Metal inventory','Initial total','Current total','Difference'],a.balance.map(b=>[b.id,`${f(b.initial)} g`,`${f(b.current)} g`,`${f(b.error)} g`]))}${calc('Total metal mass = electrode substrates + deposited metal + analytical metal in both electrolyte compartments, including precipitates. Gas and solvent-volume bookkeeping is separate; fixed solution volume is an approximation.')}<p>${esc(a.surface)}</p>`)+
    card('Time series',`<p>Charts show calculated trajectories; instrument readings and concentrations are included in the table and CSV. Sampling every ${e.config.sampleInterval} s; most recent 7,200 records retained, while charge and product totals remain cumulative.</p><div class="el-two">${[['current','Current (A) vs time (s)'],['voltage','Voltage (V) vs time (s)'],['charge','Charge (C) vs time (s)'],['leftMass','Left electrode mass (g) vs time (s)'],['rightMass','Right electrode mass (g) vs time (s)'],['hydrogen','Hydrogen (mL) vs time (s)'],['oxygen','Oxygen (mL) vs time (s)'],['leftPH','Left pH vs time (s)'],['rightPH','Right pH vs time (s)'],['temperature','Temperature (°C) vs time (s)']].map(([key,label])=>chart(e.records,'time',key,label)).join('')}</div><details><summary>Recorded measurements</summary>${table(['t (s)','V','A','C','T (°C)','pH L / R','mS/cm','Mass L / R (g)','H₂ / O₂ (mL)'],e.records.slice(-100).map(r=>[r.time,f(r.voltage),f(r.current),f(r.charge),f(r.temperature),`${f(r.leftPH)} / ${f(r.rightPH)}`,f(r.conductivity*1000),`${f(r.leftMass)} / ${f(r.rightMass)}`,`${f(r.hydrogen)} / ${f(r.oxygen)}`]))}</details>${button('export-csv','Export measurements · CSV')}`,'el-graphs');
}
function advanced(e){
  const cfg=e.config,a=e.advanced;
  const value=(key,fallback)=>a?.parameters[key]??fallback;
  return card('Advanced model controls',`<p>These parameters explore assumptions. They are not fitted reaction constants or a guarantee of a real material’s behavior. Switch output off before applying changes.</p>${form(input('kineticScale','Main-cell exchange-current multiplier',cfg.kineticScale,.001,1000)+input('diffusion','Assumed diffusion coefficient (cm²/s)',cfg.diffusion,1e-7,1e-4)+input('diffusionLayer','Unstirred diffusion layer (cm)',cfg.diffusionLayer,.001,.2)+input('collection','Gas collection fraction',cfg.collection,0,1),'configure','Apply model parameters')}
    <p>Stirring divides the cathodic layer thickness by four. Solution resistance uses spacing, area and calculated conductivity. Separator resistance and ion selectivity are selected in the cell setup.</p>`)+
    card('Polarization, Butler–Volmer and cyclic voltammetry',`<p>Each study runs an independent virtual comparison without consuming the main cell. CV treats a single metal couple, capacitive current, series resistance and a finite material inventory. Use a divided Zn/Cu cell with galvanic mode in the main controls to explore electricity generation.</p>
    ${form(select('type','Study',[['polarization','Full-cell polarization / Tafel plot'],['bv','Reversible Butler–Volmer / Tafel plot'],['cv','Cyclic voltammetry of a metal couple']],a?.type||'polarization')+select('ion','Metal couple',[['Cu','Cu²⁺ / Cu'],['Zn','Zn²⁺ / Zn'],['Ag','Ag⁺ / Ag'],['Ni','Ni²⁺ / Ni'],['Fe','Fe²⁺ / Fe']],value('id','Cu'))+input('maximum','Polarization maximum (V)',value('maximum',5),.1,30)+input('exchange','Single-couple i₀ (A/cm²)',value('exchange',.001),1e-9,.1)+input('alpha','Transfer coefficient α',value('alpha',.5),.1,.9)+input('capacitance','Double-layer capacitance (µF/cm²)',value('capacitance',20),0,1000)+input('start','CV start (V vs SHE)',value('start',.5),-2,2)+input('vertex','CV vertex (V vs SHE)',value('vertex',-.2),-2,2)+input('rate','CV scan rate (V/s)',value('rate',.05),.005,1)+input('cycles','CV cycles',value('cycles',1),1,3,1),'advanced','Run independent model study')}
    ${a?`<p>${esc(a.note)}</p>${calc(a.equation)}<p class="sl-small">Parameters: ${esc(JSON.stringify(a.parameters))}</p><div class="el-two">${chart(a.points,a.type==='bv'?'eta':'voltage','current',a.type==='cv'?'Cyclic voltammogram · applied V vs SHE → A':a.type==='bv'?'Overpotential (V) → kinetic current (A)':'Applied voltage (V) → current (A)')}${a.type==='cv'?electroChart(a.points,'time',[{key:'faradaic',name:'Faradaic A'},{key:'capacitive',name:'Capacitive A'}],'Time (s) → Faradaic and double-layer current (A)'):chart(a.points.filter(r=>r.logCurrent!==null),'eta','logCurrent','Tafel coordinates · η (V) → log10(|j| / [A cm⁻²])')}</div>${a.type==='cv'?`<p>Metal inventory closure error: ${f(a.balanceError)} g.</p>`:''}<details><summary>All computed points and substituted values</summary>${table(['Point','Values'],a.points.map((r,i)=>[i,esc(JSON.stringify(r))]))}</details>`:''}`,'el-advanced');
}
function report(e){const a=electroCalculations(e),last=a.lastOperatingReading;
  const reactions=direction=>a.recorded.filter(r=>r.direction===direction).map(r=>`${r.label} (${f(r.share*100)}% of run charge)`).join('; ')||'No charge transferred yet.';
  const comparison={cathode:reactions('reduction'),anode:reactions('oxidation'),voltage:`Current-equilibrium decomposition ${f(a.preview.decomposition)} V; last powered reading ${f(last?.measured.voltage)} V`,current:`Last powered supply reading ${f(last?.measured.current)} A; time-average ${e.time?f(e.charge/e.time):'—'} A`,products:a.recordedOverall,mass:`Left ${f(metalMass(e.electrodes.left)-e.electrodes.left.initialMass)} g; right ${f(metalMass(e.electrodes.right)-e.electrodes.right.initialMass)} g`,gas:`H₂ ${f(gasVolume(e.gases.H2,e.temperature))} mL; O₂ ${f(gasVolume(e.gases.O2,e.temperature))} mL; Cl₂ ${f(gasVolume(e.gases.Cl2,e.temperature))} mL`};
  return card('Interpret and preserve this investigation',`<p>Compare the predictions you recorded with the observed synthetic results. A model that balances charge and matter still needs experimental validation of its kinetic and transport assumptions. Recorded pathways and the last powered reading remain here after switching off.</p>${table(['Your prediction','Recorded prediction','Compare with'],PREDICTIONS.map(([id,label])=>[label,esc(e.predictions[id]||'Not recorded'),esc(comparison[id])]))}
    <h3>Recorded electrode reactions</h3>${table(['Electrode','Reaction','Integrated partial charge','Reaction amount','Calculation'],a.recorded.map(r=>[esc(r.side),esc(r.label),`${f(r.charge)} C`,`${f(r.amount)} mol`,calc(`n = Q_partial/(zF) = ${r.charge}/(${r.n} × ${EC.F}) = ${r.amount} mol. Share = Q_partial/Q_run = ${r.charge}/${e.charge} = ${r.share}. These cumulative quantities survive switching off or reversing the leads.`)]))}<p class="og-equation">${esc(a.recordedOverall)}</p><p class="sl-small">This overall equation combines the pathways with the largest cumulative oxidation and reduction charge. Parallel reactions and changes during the run are retained in the table.</p>
    <div class="sl-row">${button('snapshot','Save to shared lab notebook')}${button('export-report','Download report · Markdown')}${button('export-html','Download report with graphs · HTML')}${button('export-json','Download complete run · JSON')}</div>
    <h3>Sources and scope</h3><ul>${ELECTRO_SOURCES.map(([name,url])=>`<li><a href="${url}" target="_blank" rel="noreferrer">${esc(name)}</a></li>`).join('')}</ul><p>Standard potentials and physical constants are reference quantities. Exchange currents, diffusion layers, passive-film factors, collection losses and surface-quality judgments are teaching assumptions. Electrolyte activities, gas solubility, chloride complexes, chlorine hydrolysis, detailed corrosion and spatial fields are not exhaustively modeled. Bulk conductivity of electrodes is representative; it is distinct from electrolyte conductivity.</p><details><summary>Procedure log · ${e.operations.length} operations</summary><ol>${e.operations.map(x=>`<li>${x.time} s · ${esc(x.message)} · ${esc(JSON.stringify(x.args))}</li>`).join('')}</ol></details>`,'el-report');}
export function electroView(e,{shelf='',selected='',panel='cell',running=false,guided=false,canUndo=false,selectedTerminal=null,supplyDraft=null,predictionDraft=null}={}) {
  const p=electroPreview(e),predicted=PREDICTIONS.every(([id])=>e.predictions[id]);
  return `<div class="sl-context"><span>Electrochemistry · shared workbench</span><span>${e.volume} mL · <span data-el-live="time">${f(e.time)} s</span></span><button class="sl-button" data-lab="undo" ${canUndo?'':'disabled'}>Undo operation</button></div>
    ${guided?`<details class="sl-guide" open><summary>Electrochemistry investigation · follow the evidence</summary><ol><li>${e.volume?'Ready':'Next'}: inspect the prepared electrolyte, electrodes and settings.</li><li>${predicted?'Recorded':'Needed'}: record seven predictions, including uncertain ones.</li><li>${p.wiring.closed?'Connected':'Needed'}: wire the cell and review the shared ventilation warnings.</li><li>${e.charge?'Recorded':'Needed'}: enable the output, advance time and read the instruments.</li><li>Compare half-reaction shares, Faraday calculations and measurements; save the report to the shared notebook.</li></ol></details>`:''}
    <div class="el-workspace-nav" id="el-workspace-nav"><nav class="og-tabs el-view-tabs" role="tablist" aria-label="Electrochemistry instruments">${[['cell','Cell & circuit'],['results','Measurements & equations'],['advanced','Advanced model testing'],['report','Report & notebook']].map(([id,label])=>`<button type="button" id="el-tab-${id}" class="sl-button" data-lab="electro-panel" data-panel="${id}" role="tab" aria-selected="${id===panel}" aria-controls="el-view" tabindex="${id===panel?0:-1}" ${id===panel?'aria-current="page"':''}>${label}</button>`).join('')}</nav>
      <div class="el-quick-controls"><div class="el-quick-status"><span class="el-output-state ${e.power?'is-on':''}">${running?'RUNNING':e.power?'OUTPUT ON':'STOPPED'}</span><span data-el-live="time">${f(e.time)} s</span><span data-el-live="charge">${f(e.charge)} C</span></div><div class="el-quick-actions">${button('run',running?'Running…':'Start',`id="el-quick-start" ${running?'disabled':''}`)}${button('pause','Stop',`id="el-quick-stop" ${running||e.power?'':'disabled'}`)}<button type="button" class="sl-button" data-lab="new-run">New run</button><button type="button" class="sl-button" data-lab="restart-free">Clean desk</button></div></div>
    </div>
    <div id="el-view" role="tabpanel" aria-labelledby="el-tab-${panel}" tabindex="0">${panel!=='cell'?`<div class="el-view-update"><span>View captured at ${f(e.time)} s. ${running?'The run continues while you inspect this view.':''}</span>${button('refresh-view','Refresh this view')}</div>`:''}
    ${panel==='cell'?consoleView(e,running,selectedTerminal,supplyDraft,predictionDraft):''}<div class="og-layout el-layout"><aside class="sl-panel sl-inventory">${shelf}</aside><div class="og-content">${panel==='cell'?controls(e,selected):panel==='results'?results(e):panel==='advanced'?advanced(e):report(e)}</div></div></div>`;
}
// Update changing readings without replacing the buttons, forms, tabs or focus.
export function updateElectroLive(e){
  for(const el of document.querySelectorAll('[data-el-live="time"]'))el.textContent=`${f(e.time)} s`;
  for(const el of document.querySelectorAll('[data-el-live="charge"]'))el.textContent=`${f(e.charge)} C`;
  const current=document.querySelector('.el-console .el-cell');
  if(current){
    const template=document.createElement('template');template.innerHTML=electroArtwork(e,true,null,false);
    const next=template.content.querySelector('.el-cell');current.className=next.className;
    current.querySelector('svg').replaceWith(next.querySelector('svg'));
    for(const selector of ['.el-scene-heading','.el-electrode-key'])current.querySelector(selector).replaceChildren(...next.querySelector(selector).childNodes);
    const p=electroPreview(e);document.querySelector('.el-circuit-status').textContent=`${p.wiring.status} · ${p.regulation}`;
  }
}
export function electroFormArgs(control){const form=control.form||control.closest('form'),args={};if(!form)return args;for(const el of form.elements){if(!el.name)continue;args[el.name]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&(!el.value||!el.checkValidity()))throw Error('Check the instrument values and their allowed ranges.');}return args;}
export function electroPrintable(e){return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Electrochemistry report · Titravelle</title><style>body{font:14px system-ui;max-width:1100px;margin:30px auto;color:#243c38}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:8px;border:1px solid #ccd8d0;text-align:left}svg{max-width:100%}section{margin:25px 0}details{margin:12px 0}button,form{display:none}.el-two{display:grid;grid-template-columns:1fr 1fr;gap:20px}a{color:#285d60}@media print{section,figure{break-inside:avoid}.el-two{display:block}}</style><body><h1>Electrochemistry investigation</h1><p>Simulated measurements from an explicit teaching model. Not a validated physical operating procedure.</p>${report(e)+electroArtwork(e)+results(e)+(e.advanced?advanced(e):'')}</body></html>`.replace(/<button\b[\s\S]*?<\/button>/g,'').replace(/<form\b[\s\S]*?<\/form>/g,'').replace(/<details\b[^>]*>/g,'<details open>');}
