import {ROUTES,MINERAL_STEPS,CONFIDENCE,OBS_FIELDS,LANE_NAMES,TARGETS,INSTRUMENTS,MINERAL_SOURCES} from './mineral-data.js';
import {mineralComplete,mineralComparison,mineralPresentation,mineralConclusionDraft} from './mineral-engine.js';
import {escapeHTML as esc} from './lab-shelf.js';
import {mineralPreparationView,mineralWorkbenchView} from './mineral-workbench.js';
const n=x=>Number.isFinite(x)?Number(x.toPrecision(4)).toLocaleString('en-US',{maximumSignificantDigits:4}):'—';
const button=(action,label,extra='')=>`<button type="button" class="sl-button" data-mineral="${action}" ${extra}>${label}</button>`;
const table=(heads,rows)=>`<div class="sl-table-wrap"><table class="sl-table"><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const colours={colourless:'#e1f0ed',white:'#f0eee2',yellow:'#e5c84f',pink:'#ce88a3',purple:'#86528b',brown:'#594639',blue:'#5576a2'};
function vial(result,label){
  const fill=colours[result.colour]||colours.colourless;
  return `<article class="mn-vial-card"><h4>${esc(label)}</h4><svg viewBox="0 0 140 140" role="img" aria-label="${esc(result.description)}"><ellipse cx="70" cy="128" rx="35" ry="5" fill="#274c4b12"/><path d="M43 21V107Q43 125 70 125Q97 125 97 107V21" fill="#f1f8f6" stroke="#819f98" stroke-width="2"/><path d="M46 66Q70 70 94 66V107Q94 122 70 122Q46 122 46 107Z" fill="${fill}" opacity=".9"/><ellipse cx="70" cy="66" rx="24" ry="4" fill="${fill}" stroke="#758f8733"/>${result.precipitate!=='None visible'&&result.precipitate!=='No visible solid'?`<path d="M47 113L54 108 59 114 66 108 71 111 79 107 85 114 93 110V115Q70 128 47 115Z" fill="${result.colour==='yellow'?'#c3a529':'#c8c7b9'}"/>`:''}<ellipse cx="70" cy="21" rx="27" ry="5" fill="none" stroke="#819f98" stroke-width="2"/><path d="M50 30V60" stroke="#fff" stroke-width="3"/></svg><p>${esc(result.description)}</p>${result.absorbance!==undefined?`<strong>${n(result.absorbance)} AU</strong><p class="sl-small">Synthetic ${result.zeroed?'blank-zeroed ':''}absorbance; uncalibrated group response.</p>`:''}</article>`;
}
function assayView(s,route,presentation){
  const r=s.runs[route];
  return Object.entries(r.assays).map(([id,lanes])=>`<section class="sl-panel mn-card"><h3>${esc(MINERAL_STEPS[route].find(st=>st.id===id).title)}</h3><div class="mn-vials">${Object.entries(lanes).map(([lane,result])=>vial(result,LANE_NAMES[lane])).join('')}</div>${presentation.guidance?'<p class="sl-small mn-advice">Match the unknown to both controls. A responding blank or failed positive control invalidates an apparent sample result. A matrix spike tests response in the sample matrix; it does not measure extraction recovery.</p>':''}</section>`).join('');
}
function observation(s,presentation){
  const p=s.pending;if(!p)return '';
  return `<details class="sl-panel mn-card mb-notes" id="mn-observation-notes"><summary>Record the observed result</summary><section class="sl-panel mn-card mn-observation" id="mn-observation" tabindex="-1"><div class="sl-eyebrow">RECORD BEFORE CONTINUING</div><h2>${esc(p.route)} · ${esc(p.title)}</h2><p>${esc(p.reagent)} · ${n(p.duration)} model seconds. These timings are an animation/teaching clock, not a real procedure.</p>${presentation.equations&&p.equation?`<p class="mn-equation">${esc(p.equation)}</p>`:''}<form id="mn-record-form"><div class="mn-observation-fields">${OBS_FIELDS.map(([id,label])=>`<label>${esc(label)}<textarea id="mn-observe-${id}" name="${id}" data-min-observation="${id}" required maxlength="3000" rows="${id==='controls'?4:2}">${esc(p.draft[id])}</textarea></label>`).join('')}</div><label class="sl-check"><input type="checkbox" name="reviewed" required> I reviewed these observations and wrote my interpretation.</label>${button('record','Save observation & continue','id="mn-record"')}</form></section></details>`;
}
function conclusionView(s,route,presentation){
  const r=s.runs[route],draft=mineralConclusionDraft(s,route);
  if(r.conclusion)return `<div class="mn-conclusion">${presentation.feedback?`<div class="mn-model-feedback"><h3>${esc(r.conclusion.result)}</h3><strong>${esc(r.conclusion.confidence)}</strong><p>${esc(r.conclusion.reason)}</p></div>`:'<h3>Your recorded conclusion</h3>'}<p>Your conclusion: <strong>${esc(r.learner.confidence)}</strong> — ${esc(r.learner.reason)}</p></div>`;
  return `<form id="mn-conclusion-form" data-route="${esc(route)}">
    ${presentation.guidance?'<p class="mn-advice">Review the sample and every control before accepting a claim. A positive result remains qualitative.</p>':''}
    <label>Your confidence<select id="mn-conclusion-confidence" name="confidence" data-min-conclusion="confidence" required><option value="" ${draft.confidence?'':'selected'}>Choose your confidence</option>${CONFIDENCE.map(c=>`<option value="${esc(c)}" ${draft.confidence===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label>
    <label>Your reasoning<textarea id="mn-conclusion-reason" name="reason" data-min-conclusion="reason" required maxlength="3000" rows="3">${esc(draft.reason)}</textarea></label>
    <label class="sl-check"><input id="mn-conclusion-compared" type="checkbox" name="compared" data-min-conclusion="compared" ${draft.compared?'checked':''} required> I compared the unknown with the blank and positive control, and considered the spike when available.</label>
    <p class="sl-small">This draft is saved with aliquot ${esc(route)}. Record it when your conclusion is ready.</p>
    ${button('conclude','Record conclusion',s.pending?'disabled':'')}</form>`;
}
function routeView(s,hood,presentation,selectedReagent){
  const route=s.route,r=s.runs[route],steps=MINERAL_STEPS[route],activeIndex=s.pending?.route===route?r.index-1:r.index,st=steps[activeIndex];
  return `<section class="sl-panel mn-card" id="mn-action" tabindex="-1"><div class="sl-eyebrow">ALIQUOT ${esc(route)} ${esc(ROUTES[route])}</div><h2>${st?'Analytical sequence':'Compare the evidence and conclude'}</h2><details class="mn-sequence" ${presentation.guidance?'open':''}><summary>${r.index} of ${steps.length} stages performed${s.pending?' - result to record':''}</summary><ol class="mn-steps">${steps.map((step,i)=>`<li class="${i===activeIndex?'is-current':''}">${r.skipped.includes(step.id)?'Omitted':i<activeIndex?'Recorded':i===activeIndex?s.pending?.route===route?'Result to record':'Next':'Later'}: ${esc(step.title)}</li>`).join('')}</ol></details>${st&&presentation.guidance?`<p class="mn-advice">${esc(st.advice)}</p>`:''}${st&&presentation.equations&&st.equation?`<p class="mn-equation">${esc(st.equation)}</p>`:''}${!st&&!s.pending?conclusionView(s,route,presentation):''}</section>
    ${st||s.pending?mineralWorkbenchView(s,{hood,selectedReagent,guidance:presentation.guidance}):''}
    ${observation(s,presentation)}
    ${r.exam?`<section class="sl-panel mn-card"><h3>Microscope · three fields</h3><div class="mn-grains">${r.exam.map((description,i)=>`<article><svg viewBox="0 0 120 85" role="img" aria-label="${esc(description)}"><circle cx="60" cy="42" r="38" fill="#e8eeea" stroke="#426d65" stroke-width="3"/><path d="M43 19L77 25 83 49 65 68 36 51Z" fill="${['#d8ddd8','#555e58','#af7e3d'][i]}" stroke="#697870"/><path d="M43 19L65 40 83 49M65 40V68M65 40L36 51" fill="none" stroke="#fff6"/></svg><h4>Field ${i+1}</h4><p>${esc(description)}</p></article>`).join('')}</div><p class="sl-small">Illustrative grain fields, not a mineral identification atlas. Compare the same field in SEM-EDS after the classical investigation.</p></section>`:''}
    ${r.radiation?`<section class="sl-panel mn-card"><h3>Radiation comparison</h3><p>Background: <strong>${n(r.radiation.background)} counts</strong> · Sample: <strong>${n(r.radiation.sample)} counts</strong> in ${n(r.radiation.seconds)} simulated seconds.</p><p>Radioactivity neither proves nor excludes REEs. Counts are not a dose estimate or a safety clearance.</p></section>`:''}${assayView(s,route,presentation)}`;
}
function reportView(s,presentation){
  const rows=Object.entries(ROUTES).map(([id,name])=>{const r=s.runs[id];return [name,{A:'HNO₃ extraction / chloride',B:'Chloride extraction',C:'Chloride / NH₄Cl',D:'Mineral / digestion screen'}[id],{A:'Thiosulfate',B:'SnCl₂ / controls',C:'Precipitation / controls',D:'Oxalate / Arsenazo III'}[id],presentation.feedback?r.conclusion?.result||'Not concluded':r.learner?'Learner conclusion recorded':'Not concluded',(presentation.feedback?r.conclusion?.confidence:r.learner?.confidence)||'Not recorded'];});
  return `<section class="sl-panel mn-card"><h2>Analytical report</h2>${table(['Element/group','Primary test','Confirmation','Result','Confidence'],rows)}<p>No colour-to-ppm, g/t or percentage conversion is made. These are uncalibrated qualitative screens.</p><div class="sl-row">${button('snapshot','Save to shared notebook')}${button('export-report','Download report')}${button('export-csv','Download observation CSV')}</div></section>
    ${presentation.confirmation?`<section class="sl-panel mn-card" id="mn-instruments"><h2>Challenge the conclusions with instruments</h2><p>${mineralComplete(s)?'All four conclusions are recorded. Choose a tracked portion and a virtual method.':'Complete and conclude all four classical routes first. The original composition stays hidden until then.'}</p><p>A small analytical subportion is reserved for each submission. The parent reference remains available. Reporting limits below are illustrative settings, not guaranteed instrument capabilities.</p><form id="mn-instrument-form"><div class="sl-controls"><label>Method<select name="method">${Object.entries(INSTRUMENTS).map(([id,m])=>`<option value="${id}">${esc(m.name)}</option>`).join('')}</select></label><label>Source portion<select name="source">${['Original','E','A','B','C','D'].map(id=>`<option value="${id}">${id}${id==='Original'?' · preserved reference':id==='E'?' · reserve':''}</option>`).join('')}</select></label><label>Material submitted<select name="fraction"><option value="bulk">Bulk / all retained fractions</option><option value="solution">Separated solution only</option><option value="solid">Insoluble residue only</option></select></label><label>SEM-EDS field<select name="grain"><option value="0">Field 1 · colourless grains</option><option value="1">Field 2 · metallic/dark grains</option><option value="2">Field 3 · amber grains</option></select></label></div>${button('instrument','Submit virtual analytical portion',!mineralComplete(s)?'disabled':'')}</form></section>`:'<section class="sl-panel mn-card" id="mn-assessment-notice"><h2>Assessment presentation</h2><p>Instrument submission, model interpretations, equations and simulator answers are withheld. Recorded observations and your conclusions remain available.</p></section>'}
    ${s.revealed&&presentation.truth?`<section class="sl-panel mn-card mn-truth" id="mn-truth" tabindex="-1"><div class="sl-eyebrow">SIMULATOR GROUND TRUTH · REVEALED AFTER CONCLUSIONS</div><h2>What the original model contained</h2><p>These values come from the hidden simulation recipe, separately from the simulated instrument readings. They describe the processed concentrate, not the original river sand or an ore reserve.</p>${table(['Element','Original bulk (mg/kg)'],TARGETS.map(id=>[id,n(s.hidden.ppm[id])]))}<details><summary>Model mineral matrix and sampling</summary>${table(['Mineral','Matrix share (%)'],s.hidden.minerals.map(r=>[r.name,n(r.fraction*100)]))}<p>The matrix is normalized separately from trace target additions. Nugget distribution: ${s.nugget?'ON · 90% of Au/Pt is assigned to three particles per element':'OFF · uniform target allocation'}. Both native and mineral-bound target carriers are simplified.</p></details>${table(['Route','Bulk / route mg/kg','Your confidence','Comparison'],mineralComparison(s).map(r=>[r.name,`${n(r.bulk)} / ${n(r.aliquot)}`,r.confidence,`${r.outcome}. ${r.reason}`]))}</section>`:''}
    ${s.instruments.map(run=>`<section class="sl-panel mn-card"><h3>${esc(INSTRUMENTS[run.method].name)} · ${esc(run.source)} / ${esc(run.fraction)}</h3><p>${esc(INSTRUMENTS[run.method].note)}</p><p>${run.method==='sem'?`Field ${n(run.grain+1)}: selected-grain observations; no bulk grade is inferred.`:'Concentrations are expressed per original sample mass. A solution/residue result is the recovered fraction on that basis, not a solution concentration or a total grade.'}</p>${table(['Element','Virtual result','Illustrative limit (mg/kg)'],run.readings.map(r=>[r.element,r.limit===null?'Not supported':r.value===null?'Below reporting limit':run.method==='sem'?'Detected in selected grain':`${n(r.value)} mg/kg`,r.limit===null?'—':n(r.limit)]))}</section>`).join('')}
    <details class="sl-panel mn-card"><summary>Observation notebook · ${s.journal.length} records</summary>${s.journal.map(row=>`<article class="mn-journal"><h3>${esc(row.route)} · ${esc(row.title)}</h3><p>${esc(row.reagent)} · ${n(row.time)} model seconds</p>${row.procedure?.length?`<details><summary>Performed apparatus operations</summary><ol>${row.procedure.map(line=>`<li>${esc(line)}</li>`).join('')}</ol></details>`:''}<dl>${OBS_FIELDS.map(([id,label])=>`<dt>${esc(label)}</dt><dd>${esc(row.draft[id])}</dd>`).join('')}</dl></article>`).join('')}</details>`;
}
export function mineralView(s,{shelf='',ventilationOn=false,panel='route',canUndo=false,mode='guided',selectedReagent=''}={}){
  const presentation=mineralPresentation(mode);
  return `<div class="sl-context"><span>Mineral analysis · ${esc(s.code)} · ${n(s.time)} model s</span><button type="button" class="sl-button" data-lab="undo" ${canUndo?'':'disabled'}>Undo operation</button><button type="button" class="sl-button" data-lab="new-run">New run</button></div>
    <section class="sl-panel mn-card"><h2>One concentrate. Four independent questions.</h2><p>The lab receives a dried, crushed, homogenised heavy-mineral concentrate after gravity and magnetic separation. Its composition is unknown. Preserve a reference, compare independent aliquots, then test your interpretation.</p><p class="sl-small">All acid digestion and hazardous reactions here are virtual teaching modules. No real preparation recipe is supplied. Virtual ventilation does not establish real laboratory safety.</p></section>
    <nav class="mn-nav" aria-label="Mineral analytical routes">${Object.entries(ROUTES).map(([id,name])=>button('select',`${id} · ${esc(name)}`,`data-route="${id}" id="mn-tab-${id}" ${panel==='route'&&s.route===id?'aria-current="page"':''}`)).join('')}${button('report','Report & confirmation',`id="mn-tab-report" ${panel==='report'?'aria-current="page"':''}`)}</nav>
    <div class="mn-layout"><div class="mn-content">${s.split?panel==='report'?reportView(s,presentation)+observation(s,presentation):routeView(s,ventilationOn,presentation,selectedReagent):mineralPreparationView(s)}</div><aside class="mn-side"><section class="sl-panel mn-card"><h3>Sample ledger</h3>${table(['Sample','Purpose','Status'],s.split?Object.entries(s.portions).map(([id,p])=>[id,id==='Original'?'Untreated reference':id==='E'?'Reserve':ROUTES[id],`${n(p.grams-p.instrumentWithdrawn)} g ${['Original','E'].includes(id)?'preserved':s.runs[id].index?'in tracked fractions':'available'}${p.instrumentWithdrawn?`; ${n(p.instrumentWithdrawn)} g analytical subportions reserved`:''}`]):[['Original','Incoming concentrate','100 g · not yet split']])}<p class="sl-small">Filtrates, residues, probes and test portions remain in the ledger. Test aliquots do not return to the preserved reference.</p></section><details class="sl-panel mn-card"><summary>Shared chemical shelf</summary>${shelf}</details><details class="sl-panel mn-card"><summary>Sources and model limits</summary><p>Extraction recoveries, visibility thresholds, interferences and instrument limits are illustrative. The model is not a universal mineral-speciation solver. It cannot predict safe conditions for real digestion or determine economic value.</p>${MINERAL_SOURCES.map(([name,url])=>`<p><a href="${url}" target="_blank" rel="noreferrer">${esc(name)}</a></p>`).join('')}</details></aside></div>`;
}
